# Generated by Django 5.2 on 2025-06-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('indicator_code', models.CharField(max_length=50)),
                ('indicator_name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('value', models.FloatField()),
            ],
        ),
    ]
