# Generated by Django 5.2 on 2025-06-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_economicindicator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='economicindicator',
            name='indicator_name',
        ),
        migrations.AlterField(
            model_name='economicindicator',
            name='country',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='economicindicator',
            name='indicator_code',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
