# Generated by Django 5.2 on 2025-06-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_remove_economicindicator_indicator_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='economicindicator',
            name='indicator_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='economicindicator',
            name='year',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
